export const CAR_TYPES = ['Civilian', 'Sport', 'Military'];
export const CAR_FIELD_TYPES = ['fuel', 'lowFuelConsumption', 'durability', 'speed'];
export const CARS = [];
export const DEFAULT_FUEL = 5;
export const WAY = 200;
export const RATIO = 0.1;
export const SPEED_RATIO = 0.05;
export const DEFAULT_DURABILITY = 100;
export const DEFAULT_SPEED = 10;